title: Chung (John) Chang
position: IT Engineer
affiliation: Research Center for Chinese Cultural Subjectivity, National Chengchi University
email: jc09830250@gmail.com, changc@nccu.edu.tw
keywords: minimal academic
google_scholar: https://scholar.google.com.tw/citations?user=i7cS0HwAAAAJ&hl=en
github_link: https://github.com/jc9830250
linkedin: https://www.linkedin.com/in/chung-chang-62a825118/?locale=en_US
avatar: ./assets/img/changc.jpg
google_analytics: 
favicon: ./assets/img/biography.png
favicon_dark: ./assets/img/biography.png
description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
canonical: 
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
